import { useMutation } from "@apollo/client";
import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useRouter } from "next/router";
import React from "react";
import { AUTH_USER } from "../../graphql/mutations";
import {
  login as loginAction,
  type User,
} from "../../redux/features/authSlice";
import { type AppDispatch, useAppDispatch } from "../../redux/store";

const Login: NextPage = () => {
  const [login] = useMutation(AUTH_USER);
  const dispatch = useAppDispatch();
  const router = useRouter();
  const submit = (event: React.FormEvent) => {
    event.preventDefault();
    event.stopPropagation();
    const form = event.target as typeof event.target & {
      email: { value: string };
      password: { value: string };
    };
    const userData = {
      email: form.email.value,
      password: form.password.value,
    };

    login({
      variables: { ...userData },
      onCompleted: (data) => {
        if (data.authUser) {
          dispatch(
            loginAction?.({
              user: data.authUser as User,
            }) as unknown as AppDispatch
          );
          router.push("/");
        } else {
          alert("Invalid Credentials");
        }
      },
      onError: (error) => {
        alert(error.message);
      },
    });
  };
  return (
    <>
      <Head>
        <title>IMDD</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-br from-[#3126b0] to-[#6d2fc4]">
        <div className="mb-12 flex min-w-full justify-between px-14 py-8">
          <span className="bg-white p-[1px]">
            <span className="bg-gradient-to-br from-[#3126b0] to-[#6d2fc4] bg-clip-text text-5xl font-extrabold uppercase italic tracking-tight text-white text-transparent sm:text-[2rem]">
              <Link href="/">IMDD</Link>
            </span>
          </span>
        </div>
        <div className="flex flex-col items-start justify-center rounded-md bg-[rgba(0,0,0,.75)] px-16 py-12">
          <h1 className="my-5 text-4xl font-medium tracking-tight text-white">
            Sign In
          </h1>
          <form className="flex flex-col" onSubmit={submit}>
            <input
              type="email"
              name="email"
              id="email"
              placeholder="Email"
              className="form-input my-3 min-w-[300px] rounded-md border-0 bg-gray-800 py-4 px-5 text-gray-600 outline-none"
              required
              aria-required
            />
            <input
              type="password"
              name="password"
              id="password"
              placeholder="Password"
              className="form-input my-3 min-w-[300px] rounded-md border-0 bg-gray-800 py-4 px-5 text-gray-600 outline-none"
              required
              aria-required
            />
            <button
              type="submit"
              className="my-5 rounded-[0.275rem] bg-gradient-to-br from-[#3126b0] to-[#6d2fc4] py-3 font-medium tracking-tight text-white"
            >
              Sign In
            </button>

            <span className="my-4 text-gray-500">
              New to IMDD?{" "}
              <Link href="/auth/register" className="text-white">
                Sign up now
              </Link>
              .
            </span>
          </form>
        </div>
      </main>
    </>
  );
};

export default Login;
