import { useQuery } from "@apollo/client";
import { Breadcrumb, Card, Sidebar, Spinner } from "flowbite-react";
import { type NextPage } from "next";
import Head from "next/head";
import { Disc, House, UsersThree, VideoCamera } from "phosphor-react";
import React from "react";
import ProtectedPage from "../../components/layout/ProtectedPage";
import Logo from "../../components/Logo";
import { GET_DASHBOARD_DATA } from "../../graphql/queries";

const Dashboard: NextPage = () => {
  const { data, loading } = useQuery(GET_DASHBOARD_DATA);

  return (
    <>
      <Head>
        <title>IMDD</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProtectedPage>
        <main className="dark flex max-h-screen min-h-screen min-w-full flex-row bg-gradient-to-r from-[#0d0d0e] to-[#0a0b0d]">
          <div className="flex max-h-screen w-1/6 flex-col px-6 py-8">
            <div className="mb-20">
              <Logo />
            </div>
            <Sidebar className="w-full !bg-gradient-to-r !from-[#0d0d0e] !to-[#0a0b0d]">
              <Sidebar.Items>
                <Sidebar.ItemGroup>
                  <Sidebar.Item
                    href="/dashboard"
                    className="!text-[#afadbd]"
                    icon={House}
                  >
                    Dashboard
                  </Sidebar.Item>
                  <Sidebar.Item
                    href="/dashboard/movies"
                    className="!text-[#afadbd]"
                    icon={Disc}
                  >
                    Movies
                  </Sidebar.Item>
                  <Sidebar.Item
                    href="/dashboard/people"
                    className="!text-[#afadbd]"
                    icon={UsersThree}
                  >
                    People
                  </Sidebar.Item>
                  <Sidebar.Item
                    href="/dashboard/companies"
                    className="!text-[#afadbd]"
                    icon={VideoCamera}
                  >
                    Companies
                  </Sidebar.Item>
                </Sidebar.ItemGroup>
              </Sidebar.Items>
            </Sidebar>
          </div>
          <div className="flex w-5/6 flex-col">
            <div className="flex min-h-[150px] w-full flex-col items-start justify-between bg-gradient-to-r from-[#3126b0] to-[#6d2fc4] py-8 px-10">
              <Breadcrumb aria-label="Breadcrumbs">
                <Breadcrumb.Item href="/">Dashboard</Breadcrumb.Item>
              </Breadcrumb>
              <h1 className="text-4xl font-bold tracking-tight text-white">
                IMDD Dashboard
              </h1>
            </div>
            <div className="flex h-[75vh] w-full flex-col items-start p-10">
              <div className="flex w-full flex-row flex-wrap justify-start">
                <div className="mr-4 min-w-[15rem] max-w-sm">
                  <Card>
                    <h2 className="text-3xl font-semibold text-white">
                      Movies
                    </h2>
                    <h4 className="text-xl font-semibold text-white">
                      {loading ? (
                        <Spinner size="md"></Spinner>
                      ) : (
                        data?.movies?.length ?? 0
                      )}
                    </h4>
                  </Card>
                </div>
                <div className="mr-4 min-w-[15rem] max-w-sm">
                  <Card>
                    <h2 className="text-3xl font-semibold text-white">
                      People
                    </h2>
                    <h4 className="text-xl font-semibold text-white">
                      {loading ? (
                        <Spinner size="md"></Spinner>
                      ) : (
                        data?.people?.length ?? 0
                      )}
                    </h4>
                  </Card>
                </div>
                <div className="mr-4 min-w-[15rem] max-w-sm">
                  <Card>
                    <h2 className="text-3xl font-semibold text-white">
                      Companies
                    </h2>
                    <h4 className="text-xl font-semibold text-white">
                      {loading ? (
                        <Spinner size="md"></Spinner>
                      ) : (
                        data?.productionCompanies?.length ?? 0
                      )}
                    </h4>
                  </Card>
                </div>
              </div>
            </div>
          </div>
        </main>
      </ProtectedPage>
    </>
  );
};

export default Dashboard;
