import { type NextPage } from "next";
import Head from "next/head";
import Link from "next/link";
import { useSelector } from "react-redux";
import Logo from "../components/Logo";
import {
  type AppDispatch,
  useAppDispatch,
  type RootState,
} from "../redux/store";
import { logout as logoutAction } from "../redux/features/authSlice";

const Home: NextPage = () => {
  const isAuthenticated = useSelector(
    (state: RootState) => state.auth.isAuthenticated
  );

  const dispatch = useAppDispatch();

  const logout = () => {
    dispatch(logoutAction?.({}) as unknown as AppDispatch);
  };

  return (
    <>
      <Head>
        <title>IMDD</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center bg-gradient-to-br from-[#3126b0] to-[#6d2fc4]">
        <div className="mb-24 flex min-w-full justify-between px-14 py-8">
          <Logo />
          {isAuthenticated ? (
            <button className="rounded-sm bg-white py-2 px-5" onClick={logout}>
              <span className="m-0 font-medium tracking-tight text-black sm:text-[1rem]">
                Logout
              </span>
            </button>
          ) : (
            <Link href={"/auth/login"} className="">
              <span className="rounded-sm bg-white py-2 px-5">
                <span className="m-0 font-medium tracking-tight text-black sm:text-[1rem]">
                  Sign In
                </span>
              </span>
            </Link>
          )}
        </div>
        <div className="container mt-24 flex flex-col items-center justify-center px-4 py-16">
          <h1 className="text-5xl font-extrabold tracking-tight text-white sm:text-[5rem]">
            Welcome to{" "}
            <span className="bg-white p-5">
              <span className="bg-gradient-to-br from-[#3126b0] to-[#6d2fc4] bg-clip-text uppercase italic text-transparent">
                IMDD
              </span>
            </span>
          </h1>
          <h3 className="mt-10 text-xl font-extrabold tracking-tight text-white sm:text-xl">
            Get information about movies, TV shows, and more.
          </h3>
        </div>
      </main>
    </>
  );
};

export default Home;
